---
name: Build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  main:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: mfinelli/jumpbox:latest
